User can view bracket with their team selections - Adrian Arias
adrianm-arias/final-project pull request #23
Opened 2022-12-06 23:08 UTC by adrianm-arias

![issue-10](https://user-images.githubusercontent.com/104106959/206044516-64afa3d6-fe8b-48c4-b47b-03f3ac8db0f5.gif)

2022-12-07 00:02 UTC, thebearingedge requested changes

2022-12-07 00:02 UTC, thebearingedge commented on client/pages/bracket.jsx
> +    }
I believe we can simplify the logic here, no loops required.

```js
if (bracketRound === 'roundof16') {
  return koStage[property] === teamId;
}
```

2022-12-07 00:02 UTC, thebearingedge commented on client/pages/bracket.jsx
> +    }
I believe we can do this part without the loop too.

```js
koStageCopy[event.target.name] = teamId;
```

2022-12-07 16:41 UTC, adrianm-arias commented on client/pages/bracket.jsx
> +    }
Hey, I tried the above solution, it does not work because 'koStage[property]' is being defined from the for in loop.

2022-12-07 23:52 UTC, thebearingedge requested changes

2022-12-07 23:52 UTC, thebearingedge commented on client/pages/bracket.jsx
> +    }
oh oh, i'm sorry my example is incorrect. I meant to use the property key directly

```js
if (bracketRound === 'roundof16') {
  return koStage.game63 === teamId
}
```

2022-12-08 00:32 UTC, thebearingedge approved these changes

2022-12-08 17:38 UTC, merged